registry:
  helm: nexus
  docker: nexus

kubernetes:
  cluster_name: minikube

dependencies:
  - repo: scalecube-seed
  - repo: scalecube-seed-2
  - repo: scalecube-seed-3
  - repo: scalecube-seed-4
    version: develop
    registry:
      helm: nexus-1
      docker: nexus-1

  exclude:
    branch: pull_request