registry:
  helm: nexus
  docker: nexus

kubernetes:
  cluster_name: minikube

dependencies:
  - owner: scalecube
    repo: exchange-seed
    exclude:
      - develop

  - owner: scalecube
    repo: exchange-cluster-manager
    exclude:
      - develop

  - owner: scalecube
    repo: exchange-event-publisher
    exclude:
      - develop

  - owner: scalecube
    repo: exchange-gateway
    exclude:
      - develop

  - owner: scalecube
    repo: exchange-operation-gateway
    exclude:
      - develop

  - owner: scalecube
    repo: exchange-market-service
    exclude:
      - develop

  - owner: scalecube
    repo: exchange-audit-service
    registry:
      helm: nexus-1
      docker: nexus-1
    exclude:
      - develop
