registry:
  helm: nexus
  docker: nexus

kubernetes:
  cluster_name: minikube
  namespaces:
    master: default
    develop: default

dependencies:
  - repo: scalecube-seed
    branch:
    - master
    - pull_request
    - develop
    helm_version: 0.0.1
    registry:
      helm: nexus-1
      docker: nexus-1