registry:
  helm: nexus
  docker: nexus

kubernetes:
  cluster_name: minikube

dependencies:
  - repo: exchange-seed
  - repo: exchange-cluster-manager
  - repo: exchange-event-publisher
  - repo: exchange-gateway
    branch: develop
  - repo: exchange-operation-gateway
    branch: develop
  - repo: exchange-market-service
    branch: develop
  - repo: exchange-audit-service
    branch: develop
    registry:
      helm: nexus-1
      docker: nexus-1
    exclude:
      - pull_request