registry:
  helm: nexus
  docker: nexus

kubernetes:
  cluster_name: minikube
  namespaces:
    master: master
    develop: ${{ .Github.repo }}

dependencies:
  - repo: scalecube-seed
    version: 0.0.1
    registry:
      helm: nexus-1
      docker: nexus-1
