registry:
  helm: nexus
  docker: nexus

kubernetes:
  cluster_name: minikube

dependencies:
  - repo: scalecube-seed
  - repo: scalecube-seed-1
  - repo: scalecube-seed-2
  - repo: scalecube-seed-3
    version: develop
    registry:
      helm: nexus-1
      docker: nexus-1
    exclude:
      - pull_request