site: rnd
environments:
  - branch: master
    environment: master

  - branch: develop
    environment: develop
      
  - branch: pull_request
    environment: pr
    
  - branch: prerelease
    environment: rc
    
  - branch: release
    environment: release
