---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.owner}}-{{.Values.repo}}
spec:
  selector:
    matchLabels:
      app: {{.Values.repo}}
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        cluster-autoscaler.kubernetes.io/safe-to-evict: "false"
        timestamp: {{ default "" .Values.timestamp | quote }}
      labels:
        app: {{.Values.repo}}
        namespace: {{.Values.namespace}}
        microservice: {{.Values.repo}}
    spec:
      serviceAccountName: {{.Values.owner}}-{{.Values.repo}}
      {{- if .Values.affinity }}
      affinity:
        {{ toYaml .Values.affinity | indent 8 }}
      {{- end }}
      {{- if .Values.tolerations }}
      tolerations:
{{ toYaml .Values.tolerations | indent 8 }}
      {{- end }}
      containers:
        - name: container-{{.Values.owner}}-{{.Values.repo}}
          image: {{ .Values.images.service.repo }}:{{ .Values.images.service.tag }}
          imagePullPolicy: Always
          resources:
            limits:
              memory: {{.Values.resources.limits.memory}}
            requests:
              memory: {{.Values.resources.requests.memory}}
              cpu: {{.Values.resources.requests.cpu}}
          ports:
            - name: port-{{.Values.serviceport}}
              containerPort: {{.Values.serviceport}}
          env:
            - name: VAULT_SECRETS_PATH
              value: v1/secretv2/{{.Values.owner}}/{{.Values.repo}}/{{.Values.namespace}}/env
            - name: VAULT_ADDR
              value: {{ .Values.vault.addr }}
            - name: VAULT_TOKEN
              value: {{ .Values.vault.token }}
            - name: VAULT_ROLE
              value: {{ .Values.vault.role }}
            - name: VAULT_JWT_PROVIDER
              value: {{ .Values.vault.jwtprovider }}
            - name: VAULT_ENGINE_VERSION
              value: {{ .Values.vault.engineversion | quote }}
            - name: NAMESPACE
              value: {{.Values.namespace}}
            - name: OWNER
              value: {{.Values.owner}}
            - name: REPO
              value: {{.Values.repo}}
            - name: SHA
              value: {{.Values.sha}}
            - name: LABELS
              value: {{.Values.labels}}
            - name: TAG
              value: {{ .Values.images.service.tag }}
            - name: logLevel
              value: {{ .Values.logging.level.root }}
            {{- range $key, $val := unset .Values.env "sample_key"}}
            - name: {{ $key }}
              value: {{ $val | quote }}
            {{- end }}
      imagePullSecrets:
        - name: gitsecret-{{.Values.repo}}
