---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.owner}}-{{.Values.repo}}
spec:
  selector:
    matchLabels:
      release: {{ .Release.Name | quote }}
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        cluster-autoscaler.kubernetes.io/safe-to-evict: "false"
        timestamp: {{ default "" .Values.timestamp | quote }}
      labels:
        labels:
          app: {{ .Chart.Name }}
          release: {{ .Release.Name | quote }}
    spec:
      serviceAccountName: {{.Values.owner}}-{{.Values.repo}}
      {{- if .Values.affinity }}
      affinity:
        {{ toYaml .Values.affinity | indent 8 }}
      {{- end }}
      containers:
        - name: container-{{.Values.owner}}-{{.Values.repo}}
          image: {{ .Values.images.service.repo }}:{{ .Values.images.service.tag }}
          imagePullPolicy: Always
          resources:
            limits:
              memory: {{.Values.resources.limits.memory}}
            requests:
              memory: {{.Values.resources.requests.memory}}
              cpu: {{.Values.resources.requests.cpu}}
          ports:
            - name: port-{{.Values.serviceport}}
              containerPort: {{.Values.serviceport}}
          env:
            - name: NAMESPACE
              value: {{.Values.namespace}}
            - name: OWNER
              value: {{.Values.owner}}
            - name: REPO
              value: {{.Values.repo}}
            - name: SHA
              value: {{.Values.sha}}
            - name: LABELS
              value: {{.Values.labels}}
            - name: TAG
              value: {{ .Values.images.service.tag }}
            - name: logLevel
              value: {{ .Values.logging.level.root }}
            {{- range $key, $val := unset .Values.env "sample_key"}}
            - name: {{ $key }}
              value: {{ $val | quote }}
            {{- end }}
      imagePullSecrets:
        - name: gitsecret-{{.Values.repo}}
      tolerations:
        - effect: NoSchedule
          key: type
          operator: Equal
          value: kubsystem
        - effect: NoExecute
          key: node.kubernetes.io/not-ready
          operator: Exists
          tolerationSeconds: 300
        - effect: NoExecute
          key: node.kubernetes.io/unreachable
          operator: Exists
          tolerationSeconds: 300

