apiVersion: v1
kind: Service
metadata:
  labels:
    chart: robokit
    app: scalecube-robokit
    release: {{ .Release.Name }}
  name: robokit-svc
  namespace: {{ .Release.Namespace }}
{{- if .Values.service.annotations }}
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
{{- end }}
spec:
  ports:
  - name: port-{{ .Values.env.PORT  | toString }}
    port: {{ .Values.env.PORT }}
    protocol: TCP
    targetPort: port-{{ .Values.env.PORT  | toString }}
  selector:
    app: scalecube-robokit
  sessionAffinity: None
  type: {{ .Values.service.type }}
