---
apiVersion: v1
kind: Service
metadata:
  name: {{.Values.repo}}
  annotations:

spec:
  selector:
    app: {{.Values.repo}}
  type: NodePort
  ports:
    - name: port-{{ .Values.service.port }}
      port: {{ .Values.serviceport }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP