apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: robokit
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`robokit.nebula.exberry.io`)
      services:
        - name: {{ .Values.repo }}
          port: {{ .Values.serviceport  }}
