apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    chart: {{ .Values.helm.chart }}
    app: {{ .Values.helm.app }}
    release: {{ .Release.Name }}
{{- if .Values.service.annotations }}
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.internalPort }}
    targetPort: port-{{ .Values.service.internalPort | toString }}
    protocol: TCP
    name: port-{{ .Values.service.internalPort | toString }}
  selector:
    app: {{ .Values.helm.app }} 
