---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: traefik
  labels:
    app: scalecube-robokit
  name: scalecube-robokit-ingress
  namespace: {{ .Values.namespace }}
spec:
  rules:
  - host: {{ .Values.ingress.hostname }}.exchange.om2.com
    http:
      paths:
      - backend:
          serviceName: robokit-svc
          servicePort: {{ .Values.env.PORT }}
