name: Robokit

on: [push]

jobs:

  docker-build-push:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ secrets.DOCKER_REGISTRY }}/${{ secrets.REPO }}:${GITHUB_REF##*/}

    - uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.DOCKER_REGISTRY }}
        username: ${{ secrets.D_USER}}
        password: ${{ secrets.D_PASS }}
    - name: push ${{ secrets.REPO }} container to registry
      run: |
        cat $DOCKER_CONFIG/*
        docker login -u ${{ secrets.D_USER }} -p ${{ secrets.D_PASS }} docker.io && docker push ${{ secrets.DOCKER_REGISTRY }}/${{ secrets.REPO }}:${GITHUB_REF##*/}

  helm-package-post:
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v1
    - name: Install Helm package
      run: |
        wget -q ${{ secrets.HELM_LINK }}/${{ secrets.HELM_TGZ }}
        tar xzfv ${{ secrets.HELM_TGZ }}
        PATH=`pwd`/linux-amd64/:$PATH && helm init --client-only
    - name: Check Helm package
      run: |
        echo 'cd helm_package'
        cd ./charts
        echo "helm lint ./${{ secrets.REPO }}"
        helm lint ./${{ secrets.REPO }}
        helm repo add JF_helm ${{ secrets.HELM_URL }} --username ${{ secrets.HELM_USER }} --password ${{ secrets.HELM_PASSWORD }} 
        helm dep up ./${{ secrets.REPO }}
        echo "helm package ./${{ secrets.REPO }}"
        helm package ./${{ secrets.REPO }}
    - name: POST Helm package
      run: |
        for helm_package in $(find . -name '*.tgz'); do curl -sSf -u ${{ secrets.HELM_USER }}:${{ secrets.HELM_PASSWORD }} -X PUT -T $helm_package "${{ secrets.HELM_REGISTRY }}/$helm_package"; done

  robokit-deploy:

    needs:
      - docker-build-push

    runs-on: ubuntu-latest

    steps:
      - name: Deploy
        run: |
          echo 'Run Robo-Kit Deploy'

