name: Helm package CI

#on:
#  push:
#    paths:
#      - 'charts/**'
#      - '.github/workflows/helm_package_push.yml'
#    branches:
#      - 'develop'
#      - 'master'
#
on:
  push:
    branches:
      - 'turn-me-off'

jobs:
  helm_package_push:
    name: Helm Package and Push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download Helm
        run: |
          curl -L https://get.helm.sh/helm-v3.0.2-linux-amd64.tar.gz | tar -xzf - --strip-component=1 linux-amd64/helm
          chmod +x helm
      - name: Package and publish to helm registry
        run: |
          for directory in `find ./charts -type d -maxdepth 1 -mindepth 1`
          do
              echo helm package for $directory
              helm lint --strict $directory || exit 42
              helm template --debug $directory
              helm package --debug $directory
              name=$(cat $directory/Chart.yaml | grep ^name: | cut -d: -f2 | cut -c 2-)
              pkg=$name-$(cat $directory/Chart.yaml | grep ^version: | cut -d: -f2 | cut -c 2-).tgz
              curl -sSf -u ${{ secrets.HELM_REGISTRY_USER }}:${{ secrets.HELM_REGISTRY_PASSWORD }} -X PUT -T $pkg ${{ secrets.HELM_REGISTRY_URL }}/scalecube/$name/$pkg
          done
